global:
  commonLabels: {}
  commonAnnotations: {}
  cardanoNetwork: preview

nodeStorageSize: 10Gi
#nodeStorageClassName: ebs-sc

syncStorageSize: 30Gi
#syncStorageClassName: ebs-sc

dbSyncImageTag: 13.1.0.2
nodeImageTag: 1.35.5
restoreSnapshot: ""
recreateDb: "N"
