---
global:
  commonLabels: {}
  commonAnnotations: {}
  postgresql:
    host: "{{ .Release.Name }}-postgresql"
    service:
      ports:
        postgresql: "5432"
    auth:
      secretName: db-user-pass
      existingSecret: db-user-pass

serviceType: NodePort
ingress:
  enabled: false
  host: ""
  tls:
    enabled: false
    secretName: ""
  annotations: {}
config:
  nodeAppInstance: development
  selfManagedConfigMapName: ""

postgresStorageSize: 8Gi
#postgresStorageClassName: ebs-sc

postgresql:
  deploy: true
  auth:
    deploySecret: true
    database: cexplorer
    username: cexplorer
    secretKeys:
      adminPasswordKey: postgres_admin_password
      userPasswordKey: postgres_password
  primary:
    persistence:
      existingClaim: postgres-data-claim
