---
global:
  commonLabels: {}
  commonAnnotations: {}
  cardanoNetwork: preview
  postgresql:
    host: "{{ .Release.Name }}-postgresql"
    service:
      ports:
        postgresql: "5432"
    auth:
      secretName: db-user-pass
      existingSecret: db-user-pass

tokenRegistryUrl: https://tokens.cardano.org
imageTag: latest
serviceType: NodePort
ingress:
  enabled: false
  host: ""
  tls:
    enabled: false
    secretName: ""
  annotations: {}
config:
  nodeAppInstance: production
  selfManagedConfigMapName: ""

# tmp volume is used when extracting state snapshots, so it might be useful to mount a large volume here
tmpVolumeMount:
  enabled: false
  #storageClassName: ebs-sc
  storageClassSize: 30Gi

postgresStorageSize: 30Gi
#postgresStorageClassName: ebs-sc

postgresql:
  deploy: true
  auth:
    deploySecret: true
    database: cexplorer
    username: cexplorer
    secretKeys:
      adminPasswordKey: postgres_admin_password
      userPasswordKey: postgres_password
  primary:
    persistence:
      existingClaim: postgres-data-claim
