apiVersion: v1
kind: Service
metadata:
  name: blockfrost
  labels:
    {{- include "blockfrost.labels" . | nindent 4 }}
    app: blockfrost
  {{- if .Values.global.commonAnnotations }}
  annotations:
    {{- include "blockfrost.annotations" . | nindent 4 -}}
  {{- end }}
spec:
  type: {{ .Values.serviceType }}
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: blockfrost
