apiVersion: v1
kind: Service
metadata:
  name: cardano-db-sync
  labels:
    {{- include "blockfrost.labels" . | nindent 4 -}}
  {{- if .Values.global.commonAnnotations }}
  annotations:
    {{- include "blockfrost.annotations" . | nindent 4 -}}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: cardano-node
      port: 3001
      targetPort: 3001
    - name: cardano-db-sync
      port: 3002
      targetPort: 3002
    - name: cardano-submit-api
      port: 8090
      targetPort: 8090
  selector:
    app: cardano-db-sync
