{{ if not .Values.postgresql.self_managed_auth_secret }}
apiVersion: v1
kind: Secret
metadata:
  name: db-user-pass
  labels:
    {{- include "blockfrost.labels" . | nindent 4 -}}
  {{- if .Values.global.commonAnnotations }}
  annotations:
    {{- include "blockfrost.annotations" . | nindent 4 -}}
  {{- end }}
data:
  postgres_db: "{{ .Values.postgresql.auth.database | b64enc }}"
  postgres_user: "{{ .Values.postgresql.auth.username | b64enc }}"
  {{ include "cardano-db-sync.postgres_pass" . }}
{{- end }}