
{{ if not .Values.config.selfManagedConfigMapName }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bf-config
  labels:
    {{- include "blockfrost.labels" . | nindent 4 -}}
  {{- if .Values.global.commonAnnotations }}
  annotations:
    {{- include "blockfrost.annotations" . | nindent 4 -}}
  {{- end }}
data:
  development.ts: |-
{{ tpl ( .Files.Get "files/development.ts" ) . | indent 4 }}
  production.ts: |-
{{ tpl ( .Files.Get "files/production.ts" ) . | indent 4 }}
{{ end }}