{{ if .Values.postgresql.auth.deploySecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.postgresql.auth.secretName }}
  labels:
    {{- include "blockfrost.labels" . | nindent 4 -}}
  {{- if .Values.global.commonAnnotations }}
  annotations:
    {{- include "blockfrost.annotations" . | nindent 4 -}}
  {{- end }}
data:
  postgres_db: "{{ .Values.postgresql.auth.database | b64enc }}"
  postgres_user: "{{ .Values.postgresql.auth.username | b64enc }}"
  {{ include "blockfrost.postgres_pass" . }}
{{- end }}