apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cardano-node-data-claim
  labels:
    {{- include "blockfrost.labels" . | nindent 4 -}}
  {{- if .Values.global.commonAnnotations }}
  annotations:
    {{- include "blockfrost.annotations" . | nindent 4 -}}
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.node.volumes.data.storageClassName }}
  storageClassName: "{{ .Values.node.volumes.data.storageClassName }}"
  {{- end }}
  resources:
    requests:
      storage: "{{ .Values.node.volumes.data.storageSize }}"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-sync-data-claim
  labels:
    {{- include "blockfrost.labels" . | nindent 4 -}}
  {{- if .Values.global.commonAnnotations }}
  annotations:
    {{- include "blockfrost.annotations" . | nindent 4 -}}
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.dbSync.volumes.data.storageClassName }}
  storageClassName: "{{ .Values.dbSync.volumes.data.storageClassName }}"
  {{- end }}
  resources:
    requests:
      storage: "{{ .Values.dbSync.volumes.data.storageSize }}"

{{ if .Values.dbSync.volumes.tmp.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-sync-tmp-claim
  labels:
    {{- include "blockfrost.labels" . | nindent 4 -}}
  {{- if .Values.global.commonAnnotations }}
  annotations:
    {{- include "blockfrost.annotations" . | nindent 4 -}}
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.dbSync.volumes.tmp.storageClassName }}
  storageClassName: "{{ .Values.dbSync.volumes.tmp.storageClassName }}"
  {{- end }}
  resources:
    requests:
      storage: "{{ .Values.dbSync.volumes.tmp.storageSize }}"
{{ end }}